language: node_js
cache:
  yarn: true
  directories:
    - node_modules
node_js:
  - '10'
  - '12'
  - '14'
  - '15'
  - '16'
sudo: false
install:
  - yarn install
script:
  - yarn lint
  - yarn test
