language: node_js
cache:
  yarn: true
  directories:
    - node_modules
node_js:
  - '22'
  - '24'
sudo: false
install:
  - corepack enable
  - yarn install --immutable
script:
  - yarn lint
  - yarn test
