// Generated by listennotes/devtools/api-sdks/sync.py javascript. Do not edit.
const { request } = require('./Request');

const addApiMethodsToClient = (client) => {
  client.search = (params = {}) => request(
    client.httpClient, "GET", "/search",
    {"path": [], "query": ["q", "sort_by_date", "type", "offset", "len_min", "len_max", "episode_count_min", "episode_count_max", "update_freq_min", "update_freq_max", "genre_ids", "published_before", "published_after", "only_in", "language", "region", "ocid", "ncid", "safe_mode", "unique_podcasts", "interviews_only", "sponsored_only", "page_size"], "body": []}, params);
  client.typeahead = (params = {}) => request(
    client.httpClient, "GET", "/typeahead",
    {"path": [], "query": ["q", "show_podcasts", "show_genres", "safe_mode"], "body": []}, params);
  client.searchEpisodeTitles = (params = {}) => request(
    client.httpClient, "GET", "/search_episode_titles",
    {"path": [], "query": ["q", "podcast_id", "podcast_id_type"], "body": []}, params);
  client.spellcheck = (params = {}) => request(
    client.httpClient, "GET", "/spellcheck",
    {"path": [], "query": ["q"], "body": []}, params);
  client.fetchRelatedSearches = (params = {}) => request(
    client.httpClient, "GET", "/related_searches",
    {"path": [], "query": ["q"], "body": []}, params);
  client.fetchTrendingSearches = (params = {}) => request(
    client.httpClient, "GET", "/trending_searches",
    {"path": [], "query": [], "body": []}, params);
  client.fetchBestPodcasts = (params = {}) => request(
    client.httpClient, "GET", "/best_podcasts",
    {"path": [], "query": ["genre_id", "page", "region", "publisher_region", "language", "sort", "safe_mode"], "body": []}, params);
  client.fetchPodcastById = (params = {}) => request(
    client.httpClient, "GET", "/podcasts/{id}",
    {"path": ["id"], "query": ["next_episode_pub_date", "sort"], "body": []}, params);
  client.deletePodcast = (params = {}) => request(
    client.httpClient, "DELETE", "/podcasts/{id}",
    {"path": ["id"], "query": ["reason"], "body": []}, params);
  client.fetchEpisodeById = (params = {}) => request(
    client.httpClient, "GET", "/episodes/{id}",
    {"path": ["id"], "query": ["show_transcript"], "body": []}, params);
  client.batchFetchEpisodes = (params = {}) => request(
    client.httpClient, "POST", "/episodes",
    {"path": [], "query": [], "body": ["ids"]}, params);
  client.batchFetchPodcasts = (params = {}) => request(
    client.httpClient, "POST", "/podcasts",
    {"path": [], "query": [], "body": ["ids", "rsses", "itunes_ids", "spotify_ids", "show_latest_episodes", "next_episode_pub_date"]}, params);
  client.fetchCuratedPodcastsListById = (params = {}) => request(
    client.httpClient, "GET", "/curated_podcasts/{id}",
    {"path": ["id"], "query": [], "body": []}, params);
  client.fetchPodcastGenres = (params = {}) => request(
    client.httpClient, "GET", "/genres",
    {"path": [], "query": ["top_level_only"], "body": []}, params);
  client.fetchPodcastRegions = (params = {}) => request(
    client.httpClient, "GET", "/regions",
    {"path": [], "query": [], "body": []}, params);
  client.fetchPodcastLanguages = (params = {}) => request(
    client.httpClient, "GET", "/languages",
    {"path": [], "query": [], "body": []}, params);
  client.justListen = (params = {}) => request(
    client.httpClient, "GET", "/just_listen",
    {"path": [], "query": [], "body": []}, params);
  client.fetchCuratedPodcastsLists = (params = {}) => request(
    client.httpClient, "GET", "/curated_podcasts",
    {"path": [], "query": ["page"], "body": []}, params);
  client.fetchRecommendationsForPodcast = (params = {}) => request(
    client.httpClient, "GET", "/podcasts/{id}/recommendations",
    {"path": ["id"], "query": ["safe_mode"], "body": []}, params);
  client.fetchRecommendationsForEpisode = (params = {}) => request(
    client.httpClient, "GET", "/episodes/{id}/recommendations",
    {"path": ["id"], "query": ["safe_mode"], "body": []}, params);
  client.submitPodcast = (params = {}) => request(
    client.httpClient, "POST", "/podcasts/submit",
    {"path": [], "query": [], "body": ["rss", "email"]}, params);
  client.fetchPlaylistById = (params = {}) => request(
    client.httpClient, "GET", "/playlists/{id}",
    {"path": ["id"], "query": ["type", "last_timestamp_ms", "sort"], "body": []}, params);
  client.fetchMyPlaylists = (params = {}) => request(
    client.httpClient, "GET", "/playlists",
    {"path": [], "query": ["sort", "page"], "body": []}, params);
  client.fetchAudienceForPodcast = (params = {}) => request(
    client.httpClient, "GET", "/podcasts/{id}/audience",
    {"path": ["id"], "query": [], "body": []}, params);
  client.fetchPodcastsByDomain = (params = {}) => request(
    client.httpClient, "GET", "/podcasts/domains/{domain_name}",
    {"path": ["domain_name"], "query": ["page"], "body": []}, params);
  client.createPlaylist = (params = {}) => request(
    client.httpClient, "POST", "/playlists",
    {"path": [], "query": [], "body": ["name", "description", "visibility", "type"]}, params);
  client.updatePlaylist = (params = {}) => request(
    client.httpClient, "PUT", "/playlists/{id}",
    {"path": ["id"], "query": [], "body": ["name", "description", "visibility", "type"]}, params);
  client.addPlaylistItem = (params = {}) => request(
    client.httpClient, "POST", "/playlists/{id}/items",
    {"path": ["id"], "query": [], "body": ["episode_id", "podcast_id", "notes"]}, params);
  client.deletePlaylistItem = (params = {}) => request(
    client.httpClient, "DELETE", "/playlists/{id}/items/{item_id}",
    {"path": ["id", "item_id"], "query": [], "body": []}, params);
  client.updatePlaylistItemNotes = (params = {}) => request(
    client.httpClient, "PUT", "/playlists/{id}/items/{item_id}",
    {"path": ["id", "item_id"], "query": [], "body": ["notes"]}, params);
  return client;
};

module.exports = { addApiMethodsToClient };
